package aplicacion_escritorio;


import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Casa
 */
public class Avisos  extends Myventana {

    /**
     * Creates new form Avisos
     */
    private Image imagen;
    public Avisos(String titulo, JDesktopPane padre, String tipo) {
        super(titulo, padre);
        
        initComponents();
        cargar();
        centrar();
    }
    public void centrar()
    {
        
        
        this.setLocation((padre.getWidth()/2)-(this.getWidth()/2), (padre.getHeight()/2)-(this.getWidth()/2));
    }        
   public void cargar()
   {
       this.setVisible(true);
       System.out.println("ventana abierta");
       padre.setEnabled(false);
       label_mensaje.setText(this.titulo);
       imagen = new ImageIcon("iconos/Cargando.gif").getImage();
       
               }
   public void settitulo(String mensaje)
   {
       label_mensaje.setText(mensaje);
   }        
   public void cerrar()
   {
        try {
            Thread.sleep(200);
        } catch (InterruptedException ex) {
            Logger.getLogger(Avisos.class.getName()).log(Level.SEVERE, null, ex);
        }
       padre.setEnabled(true);
               
       this.dispose();
   }   
           /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_mensaje = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_mensaje.setAlignment(java.awt.Label.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(label_mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label_mensaje;
    // End of variables declaration//GEN-END:variables
}
