/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aplicacion_escritorio;

import static aplicacion_escritorio.Principal.driver;
import javax.swing.ButtonGroup;
import javax.swing.JDesktopPane;

/**
 *
 * @author nacho
 */
public class Conexiones extends Myventana {

    /**
     * Creates new form Conexiones
     */
    
    private String usuario;
    private String contraseña;
    private String url;
    private String Driver;
    private String[] lista={"mysql","Sqlserver"};
    private String base;
    private String ip;
    private Conectar_datos conexion;
    private ButtonGroup grupobotones;
    private JDesktopPane padre;
    
    
    public Conexiones(String titulo, JDesktopPane padre, Conectar_datos conexion) {
        super(titulo,padre);
        initComponents();
        cargar_ventana();
        this.conexion=conexion;
        this.padre=padre;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    public void cargar_ventana()
    {
     for(int i=0; i<=lista.length-1;i++)
     Lista_conectores.addItem(lista[i]);
     grupobotones = new ButtonGroup();
     grupobotones.add(opcion_manual);
     grupobotones.add(opcion_localhost);
    }        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        Lista_conectores = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        Base_de_datos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ip_servidor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Usuario_conexion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Boton_conectar = new javax.swing.JButton();
        Boton_cancelar = new javax.swing.JButton();
        Contraseña_conexion = new javax.swing.JPasswordField();
        opcion_localhost = new javax.swing.JRadioButton();
        opcion_manual = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        boton_probar_conexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(" Base de datos");

        jLabel2.setText("Base de datos");

        jLabel3.setText("ip");

        jLabel4.setText("Usuario");

        jLabel5.setText("Contraseña");

        Boton_conectar.setText("Conectar");
        Boton_conectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_conectarMouseClicked(evt);
            }
        });
        Boton_conectar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Boton_conectarKeyPressed(evt);
            }
        });

        Boton_cancelar.setText("Cancelar");

        opcion_localhost.setSelected(true);
        opcion_localhost.setText("LocalHost");
        opcion_localhost.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                opcion_localhostStateChanged(evt);
            }
        });

        opcion_manual.setText("Manual");
        opcion_manual.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                opcion_manualStateChanged(evt);
            }
        });

        boton_probar_conexion.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        boton_probar_conexion.setText("Probar conexion");
        boton_probar_conexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_probar_conexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lista_conectores, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opcion_localhost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(opcion_manual))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ip_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Base_de_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Contraseña_conexion)
                                        .addComponent(Usuario_conexion, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Boton_conectar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_probar_conexion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Lista_conectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcion_localhost)
                    .addComponent(opcion_manual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(ip_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Base_de_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Usuario_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Contraseña_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_conectar)
                    .addComponent(Boton_cancelar)
                    .addComponent(boton_probar_conexion))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_conectarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Boton_conectarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_conectarKeyPressed
    public void recoger_datos()
    {
        base=Base_de_datos.getText();
        contraseña=Contraseña_conexion.getText();
         ip=ip_servidor.getText();
         usuario=Usuario_conexion.getText();
         switch (Lista_conectores.getSelectedIndex()) {
            case 0:
                
                this.Driver="com.mysql.jdbc.Driver";
                this.url="jdbc:mysql://"+ip+":3306/"+base;
                System.out.println(url);
              
                
             
                
     //static String url="jdbc:mysql://192.168.1.128:3306/test";
   //static String url="jdbc:sqlserver://localhost;databaseName=GESTION";
                break;
            case 1:
               this.Driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
               this.url="jdbc:sqlserver://"+ip+";databaseName="+base+";";
              
            
               break;
                
        }
    }        
    private void Boton_conectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_conectarMouseClicked
        recoger_datos();
        conexion.datos_nueva_conexion(Driver, url, usuario, contraseña);
        padre.removeAll();
    }//GEN-LAST:event_Boton_conectarMouseClicked

    private void opcion_localhostStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_opcion_localhostStateChanged
        if(opcion_localhost.isSelected())
        {
            ip_servidor.setText("localhost");
            ip_servidor.setEnabled(false);
        }    
    }//GEN-LAST:event_opcion_localhostStateChanged

    private void opcion_manualStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_opcion_manualStateChanged
        if(opcion_manual.isSelected())
        {
            ip_servidor.setText("");
            ip_servidor.setEnabled(true);
        }    
    }//GEN-LAST:event_opcion_manualStateChanged

    private void boton_probar_conexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_probar_conexionActionPerformed
        recoger_datos();
        Conectar_datos cd = new Conectar_datos(this, url);
        cd.datos_nueva_conexion(this.Driver, this.url, this.usuario, this.contraseña);
        cd.probar_conexion();
    }//GEN-LAST:event_boton_probar_conexionActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Base_de_datos;
    private javax.swing.JButton Boton_cancelar;
    private javax.swing.JButton Boton_conectar;
    private javax.swing.JPasswordField Contraseña_conexion;
    private javax.swing.JComboBox Lista_conectores;
    private javax.swing.JTextField Usuario_conexion;
    private javax.swing.JButton boton_probar_conexion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField ip_servidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton opcion_localhost;
    private javax.swing.JRadioButton opcion_manual;
    // End of variables declaration//GEN-END:variables
}
